### ISSUE TITLE
Contribute to Bellingcat's open source work

### ISSUE THREAD

**Issue by OmarShehata** [codeLabs-summer2021/3D-Model-World#1]
See: https://www.bellingcat.com/resources/2021/07/06/help-bellingcat-build-tools-for-open-source-investigators/

Bellingcat is an non profit that does investigative journalism on pretty serious topics:

> from Mexican drug lords and crimes against humanity, to tracking the use of chemical weapons and conflicts worldwide.

They use a lot of geospatial/GIS tools. They are open sourcing their work, and this could be one area to contribute to!

**Comment by CalebMcOlin** [comment]
Closed during repo overhaul. 
**Reason:** Not relevant anymore.
