### ISSUE TITLE
Set up CD (Continous Deployment) for the server

### ISSUE THREAD

**Issue by OmarShehata** [codeLabs-summer2021/3D-Model-World#11]
Once the server is set up (https://github.com/OmarShehata/codelabs-summer-2021/issues/8), we should set up an automatic deployment for it, similar to the one we'll set up for the frontend, see: https://github.com/OmarShehata/codelabs-summer-2021/issues/7

**Comment by CalebMcOlin** [comment]
Closed during repo overhaul. 

**Reason:** Not relevant anymore.
