### ISSUE TITLE
Set up Cesium ion OAuth 

### ISSUE THREAD

**Issue by OmarShehata** [codeLabs-summer2021/3D-Model-World#12]
One way to get to an initial prototype very quickly is to leverage the Cesium ion platform for (1) hosting the 3D models (2) allowing users to position it. Then all our app has to do is let the user log in, and let the user import their models. And everything else is automatically handled, like only the user who added it can move the model, etc. 

To do this:

1. Go through the tutorial here: https://cesium.com/learn/ion/ion-oauth2/. This will show you how to register a new app, and use the REST API to upload a model
2. Now, instead of uploading a model, we need to acquire a model from the user's account. There are two routes for this, get info about the model, like name and description: https://cesium.com/learn/ion/rest-api/#operation/getAsset. And to load the actual model in the viewer: https://cesium.com/learn/ion/rest-api/#operation/getAssetEndpoint. 
3. Create a basic UI that'll allow a user to enter their ion asset ID, and that'll show up in the viewer. 

I think the authentication that tutorial explains does NOT cover authenticating via the browser? If so, you'll need to make sure to do that to (instead of authenticating from the server)

**Comment by CalebMcOlin** [comment]
Closed during repo overhaul. 

**Reason:** Not relevant anymore.
