### ISSUE TITLE
CesiumJs Thoughts

### ISSUE THREAD

**Issue by randrade8311** [codeLabs-summer2021/3D-Model-World#4]
After looking into CesiumJs this is what I have to report:

- Cesium has two quick tutorials which can be very helpful to get started:
  - https://cesium.com/learn/cesiumjs-learn/cesiumjs-flight-tracker/
  - https://cesium.com/learn/cesiumjs-learn/cesiumjs-interactive-building/
- If using glitch, you could upload a glb file that has the required files for the model
- You will need a Cesium Ion account, the account will grant you access to:
  - CesiumJs (A token is required)
  - You could upload models, an Id will be provided which you could use to access the model on your site
  - CesiumJs has many commands which could be helpful
- You could use sketchfab 3D models by downloading them and uploading them to either glitch or your CesiumIon account

This is the complete flight tracker tutorial: 
  - https://glitch.com/edit/#!/holly-clover-gasosaurus?path=index.html%3A62%3A45
The plane was replaced by a jet from sketchfab

This glitch has the Fountain of the Sea Horses model where it would be located in real life: 
  - https://glitch.com/edit/#!/learned-stellar-sundae?path=index.html%3A37%3A36

**Comment by CalebMcOlin** [comment]
Closed during repo overhaul. 

**Reason:** Not relevant anymore.
