### ISSUE TITLE
Set up a basic NodeJS server

### ISSUE THREAD

**Issue by OmarShehata** [codeLabs-summer2021/3D-Model-World#8]
This is similar to setting up the frontend client (https://github.com/OmarShehata/codelabs-summer-2021/issues/6) but for the backend. This initial server should have a single route that just returns a list of model URL's, and positions. This will act as the "dummy database" to start with, so eventually it can return a dynamic list of models that users are adding, and the client will display them.

This should be written in NodeJS.

**Comment by CalebMcOlin** [comment]
Closed during repo overhaul. 

**Reason:** Not relevant anymore.
