### ISSUE TITLE
List of 3D Models

### ISSUE THREAD

**Issue by randrade8311** [codeLabs-summer2021/3D-Model-World#9]
Fountain of the Sea Horses
- Link to Sketchfab Model: 
  - https://sketchfab.com/3d-models/the-fountain-of-the-sea-horses-966b78a6e4e744d8ac4dc3be20c2de69
- Location: 
  - Philadelphia Museum of Art’s Fairmount Park
  - Google Maps:
    - https://www.google.com/maps/place/Fountain+of+the+Sea+Horses/@39.9675605,-75.1836064,216m/data=!3m1!1e3!4m5!3m4!1s0x89c6c7b6b2b9c31f:0x7caf855efb0f834c!8m2!3d39.9675752!4d-75.1836727
- Coordinates: 
  - -75.18366430124546, 39.96764308857853

Electrical Box
- Link to Sketchfab Model: 
  - https://sketchfab.com/3d-models/electrical-box-free-383a234d6d80421fbe67080048cbbc70
- Location: 
  - Anywhere on the sidewalks
- Coordinates (Used on Glitch): 
  - -75.18394092251862, 39.96782237288637
  
Cormorant Statue
- Link to Sketchfab Model: 
  - https://sketchfab.com/3d-models/cormorant-statue-da3f963385d84c258b85f70b44f3e16e
- Location: 
  - Morecambe LA4 5EZ, United Kingdom
  - Google Maps: 
    - https://www.google.com/maps/place/P.+Speak/@54.074166,-2.8671567,17z/data=!3m1!4b1!4m5!3m4!1s0x487c9fd0be01392b:0x57434672510358ad!8m2!3d54.074166!4d-2.864968
- Coordinates: 
  - -2.8650, 54.0742 (Not Exact)

**Comment by CalebMcOlin** [comment]
Closed during repo overhaul. 

**Reason:** Not relevant anymore.
